### ISSUE TITLE
Error: subscript is a logical vector with out-of-bounds TRUE values

### ISSUE THREAD

**Issue by Vermarashi** [pappewaio/AllelicImbalance#2]
Hello Everyone,

I am trying to run allele expression analysis using AllelicImbalance package with my vcf file.

I ran command and got the below error
>pathToVcf <- paste("../stroke_batch1_GT.vcf",sep="")
>VCF <- readVcf(pathToVcf,"../Homo_sapiens.GRCh38.dna.mainchrs.fa")
>gr <- granges(VCF)
>gr.filt <- gr[width(mcols(gr)[,"REF"]) == 1 | unlist(lapply(mcols(gr)[,"ALT"],width))==1]
Error: subscript is a logical vector with out-of-bounds TRUE values
In addition: Warning message:
In ref_width == 1 | alt_widths == 1 : longer object length is not a multiple of shorter object length.

Then I checked the length and found it was different for REF and ALT
>length(ref_width)
[1] 2382565
> length(alt_widths)
[1] 2416902

How, I can resolve this issue. I am new to this field. Kindly help me.

Thanks in advance.

**Comment by pappewaio** [comment]
Hi! 

You are checking if any of these conditions are TRUE
```
width(mcols(gr)[,"REF"]) == 1 
unlist(lapply(mcols(gr)[,"ALT"],width))==1
```

Alt alleles can be multi-allelic, and therefore the unlist of alt alleles can be longer than the ref. Testing that is actually the case can be step 1, even though I am quite certain that is the case for you. There is no practical reason - as I see it - to check ref == alt, but it is a good sanity test. For a sanity test you could settle with picking one of the alt alleles, or only go with the bi-allelic variants.
 
However, I do note that you might be trying to use width() for this reason, but width() is actually checking the length of the allele, i.e., becoming >1 if there is e.g., an insertion. 

The class of mcols(gr)[,"ALT"] is a standard Bioconductor class making it possible to treat lists like vectors, which can be extremely beneficial if you need to optimize your function. If you want a quick solution you could always for loop through and compare each element and treat it as a nested list.

Let me know if there is anything else I can assist with.
