### ISSUE TITLE
Bug in scanForHeterozygotes

### ISSUE THREAD

**Issue by lassefolkersen** [pappewaio/AllelicImbalance#2]
Bug in scanForHeterozygotes. A simple allelicImbalance call gave an unexplained error. It is likely a pretty rare instance since it happened in only one out of hundreds of samples:

```R
searchArea<-getAreaFromGeneNames(genes, org.Hs.eg.db)
reads <- impBamGAL(tempPathToFiles,searchArea,verbose=TRUE)
heterozygotePositions <- scanForHeterozygotes(reads,verbose=T,maxReads=150000)
```
![nooooo](https://cloud.githubusercontent.com/assets/1732847/6528671/a4772fa0-c3f1-11e4-94b7-c538387a1566.PNG)

A link to the reads object that can produce this:
https://db.tt/Bw0XUv1K

Ran debug and it happens here:
```R
for (i in 1:ncol(new)) {
    new[start[i]:(start[i] + length(toKeep[[i]]) - 1), i] <- charList[[i]][toKeep[[i]]]
}
```

It happens at col 724 of 724 (so the last). Checked the variables and report the key ones here:
```R
charList[[i]][toKeep[[i]]]
  [1] "T" "T" "A" "T" "T" "G" "G" "T" "G" "A" "A" "T" "A" "G" "C" "T" "G" "A"
 [19] "A" "A" "A" "A" "C" "A" "G" "A" "G" "G" "G" "A" "T" "T" "A" "A" "G" "T"
 [37] "C" "A" "T" "A" "T" "T" "C" "C" "G" "G" "G" "A" "A" "A" "G" "A" "G" "A"
 [55] "A" "T" "T" "A" "T" "A" "G" "T" "T" "T" "T" "T" "A" "T" "G" "C" "C" "T"
 [73] "C" "C" "T" "G" "T" "T" "G" "A" "A" "T" "A" "A" "A" "T" "G" "G" "T" "G"
 [91] "T" "C" "C" "T" "A" "A" "A" NA  NA  NA

dim(new)
[1] 18801   724

start[i]
18705

(start[i] + length(toKeep[[i]]) - 1)
18804 (((!!!!OBVIOUS PROBLEM. TOO LONG FOR THE MATRIX!)))
```
My guess is that it is the three extra NA in `charList[[i]][toKeep[[i]]]` causes this. Could be fixed with this change:
```R
new[start[i]:(start[i] + length(toKeep[[i]]) - 1), i] <- charList[[i]][toKeep[[i]]]
```
to:
```R
nucleotidesHere <- charList[[i]][toKeep[[i]]]
nucleotidesHere <- nucleotidesHere[!is.na(nucleotidesHere)]
new[start[i]:(start[i] + length(toKeep[[i]]) - 1), i] <- nucleotidesHere
```

**Comment by lassefolkersen** [comment]
Version of AllelicImbalance:
1.4.0

**Comment by pappewaio** [comment]
The bug is fixed and the changes are now in the github repository. The problem was with the conversion of cigars.
