### ISSUE TITLE
Bug in inferAltAllele

### ISSUE THREAD

**Issue by lassefolkersen** [pappewaio/AllelicImbalance#4]
I couldn't get inferAltAllele to work and it failed in a pretty non-informative way

https://db.tt/2Y5jt4IB
```R
load("smalltestset.rdata")
mcols(a)[,"alt"] <- inferAltAllele(a)
Error in NSBS(i, x, exact = exact, upperBoundIsStrict = !allow.append) : 
  subscript contains invalid names
```

For AllelicImbalance_1.5.17

**Comment by pappewaio** [comment]
In your ASEset metacolumn names, "REF" was present instead of "ref", which is the required name. Changing from "REF" to "ref" should fix the problem. Now there is also a more informative check if "ref" is missing.
